using System;
using System.Collections.Generic;
using System.Text;
using System.Collections;
using BO_SISACO;
using BDA_SISACO;

namespace BL_SISACO
{
	public partial class BLT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos:BLBase
	{
		public Boolean fnInsT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos(BOT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos poBOT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos)
		{
			BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos=new BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos();
			return loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos.fnInsT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos(poBOT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos);
		}
		public Boolean fnUpdT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos(BOT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos poBOT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos)
		{
			BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos=new BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos();
			return loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos.fnUpdT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos(poBOT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos);
		}

		public Boolean fnInsUpdT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos(BOT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos poBOT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos, out string codigo_registro_codificacion_despeje_linea_materiales_insumos)
		{
			BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos=new BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos();
			return loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos.fnInsUpdT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos(poBOT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos,out codigo_registro_codificacion_despeje_linea_materiales_insumos);
		}
		public Boolean fnDelT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos(String psCodigo_Registro_Codificacion_Despeje_Linea_Materiales_Insumos)
		{
			BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos=new BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos();
			
			return loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos.fnDelT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos(psCodigo_Registro_Codificacion_Despeje_Linea_Materiales_Insumos);
		}

		public List<BOT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos> fnSelT_Registro_Codificacion_Despeje_Linea_Materiales_InsumosAll()
		{
			BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos=new BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos();
			return loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos.fnSelT_Registro_Codificacion_Despeje_Linea_Materiales_InsumosAll();
		}

		public BOT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos fnSelT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos(String psCodigo_Registro_Codificacion_Despeje_Linea_Materiales_Insumos)
		{
			BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos=new BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos();
			return loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos.fnSelT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos(psCodigo_Registro_Codificacion_Despeje_Linea_Materiales_Insumos);
		}
		public List<BOT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos> fnSelT_Registro_Codificacion_Despeje_Linea_Materiales_InsumosDin(string psWhere,string psOrder)
		{
			BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos=new BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos();
			return loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos.fnSelT_Registro_Codificacion_Despeje_Linea_Materiales_InsumosDin(psWhere,psOrder);

		}
		public Int32[] fnSelT_Registro_Codificacion_Despeje_Linea_Materiales_InsumosMinMax()
        {
            BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos = new BDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos();
            return loBDAT_Registro_Codificacion_Despeje_Linea_Materiales_Insumos.fnSelT_Registro_Codificacion_Despeje_Linea_Materiales_InsumosMinMax();
        }


	}
}
